[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
git2 = "0.19.0"
itertools = "0.13.0"
regex = "1.11.1"
cached = "0.54.0"
